# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: |
        git remote set-url origin https://Bearer:${{ secrets.GITHUB_TOKEN }}@github.com/near-hackathon-luciferius/challenge-8-rocketo-dao-dashboard
        npm --no-git-tag-version version 1.0.${{ github.run_number }}
        npm ci
        npm run deploy --if-present
